name: Deploy Astro Blog to GitHub Pages

on:
  push:
    branches:
      - main  # nếu repo chính của bạn là main

permissions:
  contents: write      # cho phép push lên gh-pages
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node & pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      # 3️⃣ Cài dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 4️⃣ Build Astro
      - name: Build Astro project
        run: pnpm run build

      # 5️⃣ Deploy lên GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages   # branch chứa site đã build
          cname: ''                  # để trống nếu không dùng custom domain
